# Generated by Django 4.2.16 on 2024-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
